### ISSUE TITLE
Remove embedded plunk from the home page 

### ISSUE THREAD

**Issue by boghyon** [SAP/openui5-website#151]
## Problem
Currently, visitors of the https://openui5.org see the following on the front page:

![openui5 embedded plunk on the front page broken](https://user-images.githubusercontent.com/12143247/90159039-15dc2700-dd90-11ea-9ace-787db61f001c.gif)

As if displaying a warning in the preview panel is not bad enough, clicking on any of the buttons (<kbd>Back</kbd>, <kbd>Proceed</kbd>, <kbd>Dismiss</kbd>) **doesn't actually do anything.**

Plunker was very popular in the AngularJS days and it's still useful for e.g. sharing small demos or code snippets on various Q&A platforms. But it's unfortunately poorly maintained, broken, and ad-supported which is, frankly speaking, quite embarrassing compared to how other frameworks showcase their _key concepts_ on their homepage (See https://svelte.dev).

## Solution?
Simply removing the plunk from the homepage would reduce the impression that OpenUI5 itself is not well-maintained.

**Comment by pavelkornev** [comment]
Hello Boghyon,

thanks for creating this issue. The code snippet is planned to be replaced with CodeSandbox soon.

BR,
Pavel

**Comment by pavelkornev** [comment]
FYI: it's now replaced with CodeSandbox...
