### ISSUE TITLE
Visual bugs after merged PR #4

### ISSUE THREAD

**Issue by pavelkornev** [SAP/openui5-website#18]
After merged PR #4 the following visual bugs can be observed:

- the is no space between links in the footer on some screen breakouts
- some links have underline on hover, some not
- internal links should not open in the new window

![screenshot 2019-02-06 at 09 40 59](https://user-images.githubusercontent.com/748043/52329827-fffbe200-29f3-11e9-93f2-f65a4c175db5.png)

**Comment by Michadelic** [comment]
fixed with https://github.com/SAP/openui5-website/pull/23
