### ISSUE TITLE
Code Sandbox Section Broken

### ISSUE THREAD

**Issue by BenReim** [SAP/openui5-website#330]
Instead of the code sandbox a bank container is being shown and a JS error can be observed on the dev console.

**Comment by evgenysegeda** [comment]
Is the issue in the incognito mode or also in the normal mode? If you run in the incognito mode, you need to switch off "Block third-party cookies"

**Comment by BenReim** [comment]
Correct, the reason seems to be that I've disabled third party cookies in my browser.
