### ISSUE TITLE
Wrong target page for UI5con 2018

### ISSUE THREAD

**Issue by margopolo** [SAP/openui5-website#61]
On the community landing page https://openui5.org/community/ the link on UI5con 2018 directs to the current event UI5con 2019 instead of directing to the sessions of 2018 (https://openui5.org/ui5con/material2018.html).

In addition it might make sense to consider a differentiation between upcoming and past events?

**Comment by pavelkornev** [comment]
@margopolo 
link is fixed

> In addition it might make sense to consider a differentiation between upcoming and past events?
sounds reasonable, added to TODO
