### ISSUE TITLE
Projects page: Link for "Add a new project" doesn't work

### ISSUE THREAD

**Issue by OlMue** [SAP/openui5-website#7]
Hi,

the target of the "Add a new project" link on the Projects page doesn't exist (anymore). The current link is https://github.com/SAP/openui5/tree/gh-pages/docs/CommunityProjects.md, but it probably should be https://github.com/SAP/openui5-website/blob/master/src/public/docs/CommunityProjects.md.

Thanks and best regards,
Oliver

**Comment by margopolo** [comment]
Same with the link "More Community Projects on GitHub": 
It targets to https://github.com/SAP/openui5/tree/gh-pages/docs/CommunityProjects.md but should go to https://github.com/SAP/openui5-website/tree/gh-pages/docs/CommunityProjects.md ...
